import Foundation
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case french = "fr"
    case spanish = "es"
    case japanese = "ja"
    case chinese = "zh"
    case korean = "ko"

    var id: String { rawValue }

    var localeIdentifier: String { rawValue }

    var nativeName: String {
        switch self {
        case .english: return "English"
        case .french: return "Français"
        case .spanish: return "Español"
        case .japanese: return "日本語"
        case .chinese: return "中文"
        case .korean: return "한국어"
        }
    }

    var languageCodeLabel: String {
        rawValue.uppercased()
    }

    static func resolvedFromDevice() -> AppLanguage {
        for preferred in Locale.preferredLanguages {
            let normalized = preferred.lowercased()

            if normalized.hasPrefix("fr") { return .french }
            if normalized.hasPrefix("es") { return .spanish }
            if normalized.hasPrefix("ja") { return .japanese }
            if normalized.hasPrefix("zh") { return .chinese }
            if normalized.hasPrefix("ko") { return .korean }
            if normalized.hasPrefix("en") { return .english }
        }

        return .english
    }
}

final class LocalizationManager: ObservableObject {
    private static let storageKey = "selectedAppLanguage"

    @Published private(set) var language: AppLanguage

    init(defaults: UserDefaults = .standard) {
        if let storedValue = defaults.string(forKey: Self.storageKey),
           let storedLanguage = AppLanguage(rawValue: storedValue) {
            self.language = storedLanguage
        } else {
            let resolved = AppLanguage.resolvedFromDevice()
            self.language = resolved
            defaults.set(resolved.rawValue, forKey: Self.storageKey)
        }
    }

    func setLanguage(_ language: AppLanguage) {
        guard self.language != language else { return }
        self.language = language
        UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey)
    }

    func text(_ key: String, _ arguments: CVarArg...) -> String {
        let format = Self.translations[language]?[key]
            ?? Self.translations[.english]?[key]
            ?? key

        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: Locale(identifier: language.localeIdentifier), arguments: arguments)
    }

    func moodName(_ mood: DateMood) -> String {
        switch mood {
        case .chill:
            return text("mood.chill")
        case .romantic:
            return text("mood.romantic")
        case .fun:
            return text("mood.fun")
        case .adventure:
            return text("mood.adventure")
        }
    }

    static let preview = LocalizationManager()
}

private extension LocalizationManager {
    static let translations: [AppLanguage: [String: String]] = [
        .english: [
            "content.highlight.ai.title": "AI-crafted",
            "content.highlight.ai.subtitle": "A date flow built around your vibe.",
            "content.highlight.nearby.title": "Nearby places",
            "content.highlight.nearby.subtitle": "Smart location picks around your area.",
            "content.highlight.personal.title": "Personal touch",
            "content.highlight.personal.subtitle": "Budget, mood, and your own ideas included.",
            "content.appTitle": "AI Date Planner",
            "content.hero.line1": "Plan a date that",
            "content.hero.line2": "actually feels right",
            "content.hero.subtitle": "Tell us your mood, budget, and area. We’ll turn that into a smooth, personalized date plan in seconds.",
            "content.badge.aiSuggestions": "AI suggestions",
            "content.badge.readyInSeconds": "Ready in seconds",
            "content.card.title": "From mood to route",
            "content.card.subtitle": "Find nearby spots, balance the vibe, and build a date plan with a natural rhythm.",
            "content.card.localPicks": "Local picks",
            "content.card.personalized": "Personalized",
            "content.callout.title": "Built for smooth date flow",
            "content.callout.subtitle": "Not just random places. The app tries to create a route that feels easy and coherent.",
            "content.cta.startPlanning": "Start planning",
            "content.cta.caption": "Mood, budget, location. We handle the rest.",
            "datePicker.location.unselected": "Choose an area",
            "datePicker.readiness.location": "location",
            "datePicker.readiness.mood": "mood",
            "datePicker.map.disabledPreview": "Map disabled in Preview",
            "datePicker.map.previewPlaceholder": "Map preview will appear here",
            "datePicker.title": "Date Setup",
            "datePicker.heading": "Create your date",
            "datePicker.subtitle": "Set the mood, budget, and area. We’ll turn that into a smooth date plan with nearby places and a natural flow.",
            "datePicker.section.budget.title": "Budget",
            "datePicker.section.budget.subtitle": "Set the budget range for the whole date.",
            "datePicker.section.location.title": "Location",
            "datePicker.section.location.subtitle": "Pick the area where the date should happen.",
            "datePicker.section.mood.title": "Mood",
            "datePicker.section.mood.subtitle": "Choose the overall energy you want for the date.",
            "datePicker.section.ideas.title": "Ideas",
            "datePicker.section.ideas.subtitle": "Add optional hints like cinema, aquarium, ramen, or rooftop.",
            "datePicker.location.areaNotSelected": "Area not selected",
            "datePicker.location.openMap": "Open the map to select a place and radius.",
            "datePicker.location.radiusFormat": "Search radius: %d m",
            "datePicker.ideas.placeholder": "Tell us your ideas...",
            "datePicker.ideas.charactersFormat": "%d characters",
            "common.optional": "Optional",
            "datePicker.cta.generate": "Generate plan",
            "datePicker.readiness.ready": "Everything looks ready. Generate your personalized date plan.",
            "datePicker.readiness.adjust": "Adjust your preferences before generating.",
            "datePicker.readiness.chooseFormat": "Choose your %@ to continue.",
            "datePicker.header.noAreaYet": "No area yet",
            "datePicker.header.noMoodYet": "No mood yet",
            "common.done": "Done",
            "datePicker.error.title": "Generation Error",
            "common.ok": "OK",
            "common.unknownError": "Unknown error",
            "mood.chill": "Chill",
            "mood.romantic": "Romantic",
            "mood.fun": "Fun",
            "mood.adventure": "Adventure",
            "location.search.placeholder": "Search for a place (Shibuya, Tokyo...)",
            "location.tapMapHint": "You can also tap directly on the map to choose an area.",
            "location.section.suggested": "Suggested areas",
            "location.section.results": "Search results",
            "location.noResultsYet": "No results yet",
            "location.searchRadius": "Search radius",
            "location.selectedArea": "Selected area",
            "location.pinnedArea": "Pinned area",
            "location.pinnedAreaFormat": "Pinned area (%.4f, %.4f)",
            "loading.step.finding.title": "Finding nearby spots",
            "loading.step.finding.subtitle": "Scanning the best places around your selected area.",
            "loading.step.matching.title": "Matching the vibe",
            "loading.step.matching.subtitle": "Balancing budget, mood, and your own ideas.",
            "loading.step.building.title": "Building the route",
            "loading.step.building.subtitle": "Arranging a smooth flow for the full date plan.",
            "loading.title": "Designing your date",
            "loading.subtitle": "We are picking places, shaping the mood, and building a plan that feels natural.",
            "loading.detail.nearby": "Nearby",
            "loading.detail.ai": "AI",
            "loading.detail.flow": "Flow",
            "loading.progress": "Generating a personalized plan...",
            "plan.duration.hoursMinutes": "%d h %d min",
            "plan.duration.hoursOnly": "%d h",
            "plan.duration.minutesOnly": "%d min",
            "common.flexible": "Flexible",
            "plan.title": "Your Date Plan",
            "plan.defaultSummary": "A smooth, personalized route designed around your vibe and nearby places.",
            "plan.stats.budget": "Budget",
            "plan.stats.stops": "Stops",
            "plan.stats.duration": "Duration",
            "plan.itinerary.title": "Itinerary",
            "plan.itinerary.subtitle": "A step-by-step flow for the full date.",
            "plan.stopFormat": "Stop %d",
            "plan.whyThisStop": "Why this stop",
            "plan.viewDetails": "View details",
            "plan.nextStop": "Next stop",
            "detail.addressUnavailable": "Address unavailable",
            "detail.selectedStop": "Selected stop",
            "detail.stopSpotlight": "Stop Spotlight",
            "detail.stopSpotlightSubtitle": "A place chosen to keep the date feeling natural, balanced, and memorable.",
            "detail.quickFacts": "Quick Facts",
            "detail.category": "Category",
            "common.custom": "Custom",
            "detail.estimated": "Estimated",
            "detail.coordinates": "Coordinates",
            "detail.whyItWorks": "Why It Works",
            "detail.locationPreview": "Location Preview",
            "detail.tapToOpenMaps": "Tap to open in Maps",
            "detail.preferGoogleMaps": "Prefer Google Maps?",
            "detail.openThere": "Open there",
            "detail.locationPreviewUnavailable": "Location preview unavailable",
            "options.title": "Options",
            "options.subtitle": "Adjust a few app preferences and choose the language you want to use.",
            "options.language.title": "App language",
            "options.language.subtitle": "The app starts in your device language when available, and falls back to English otherwise.",
            "options.language.current": "Current language",
            "options.launch.title": "Launch behavior",
            "options.launch.subtitle": "The introduction screen is shown only on the first launch. After that, the app opens directly on the planner."
        ],
        .french: [
            "content.highlight.ai.title": "Conçu par IA",
            "content.highlight.ai.subtitle": "Un déroulé de rendez-vous pensé selon votre vibe.",
            "content.highlight.nearby.title": "Lieux proches",
            "content.highlight.nearby.subtitle": "Des suggestions intelligentes autour de votre zone.",
            "content.highlight.personal.title": "Touche perso",
            "content.highlight.personal.subtitle": "Budget, humeur et idées personnelles pris en compte.",
            "content.appTitle": "Planificateur de date IA",
            "content.hero.line1": "Planifiez un rendez-vous",
            "content.hero.line2": "qui sonne juste",
            "content.hero.subtitle": "Indiquez votre humeur, votre budget et votre zone. Nous créons un plan de date fluide et personnalisé en quelques secondes.",
            "content.badge.aiSuggestions": "Suggestions IA",
            "content.badge.readyInSeconds": "Prêt en quelques secondes",
            "content.card.title": "De l’humeur au parcours",
            "content.card.subtitle": "Trouvez des lieux proches, équilibrez l’ambiance et construisez une date au rythme naturel.",
            "content.card.localPicks": "Sélection locale",
            "content.card.personalized": "Personnalisé",
            "content.callout.title": "Pensé pour une date fluide",
            "content.callout.subtitle": "Pas seulement des lieux au hasard. L’app essaie de créer un parcours simple et cohérent.",
            "content.cta.startPlanning": "Commencer",
            "content.cta.caption": "Humeur, budget, lieu. On s’occupe du reste.",
            "datePicker.location.unselected": "Choisir une zone",
            "datePicker.readiness.location": "lieu",
            "datePicker.readiness.mood": "humeur",
            "datePicker.map.disabledPreview": "Carte désactivée en aperçu",
            "datePicker.map.previewPlaceholder": "L’aperçu de la carte apparaîtra ici",
            "datePicker.title": "Configuration",
            "datePicker.heading": "Créez votre date",
            "datePicker.subtitle": "Définissez l’humeur, le budget et la zone. Nous en faisons un plan de date fluide avec des lieux proches et un bon enchaînement.",
            "datePicker.section.budget.title": "Budget",
            "datePicker.section.budget.subtitle": "Définissez le budget pour l’ensemble du rendez-vous.",
            "datePicker.section.location.title": "Lieu",
            "datePicker.section.location.subtitle": "Choisissez la zone où doit se dérouler le rendez-vous.",
            "datePicker.section.mood.title": "Ambiance",
            "datePicker.section.mood.subtitle": "Choisissez l’énergie générale que vous voulez donner au rendez-vous.",
            "datePicker.section.ideas.title": "Idées",
            "datePicker.section.ideas.subtitle": "Ajoutez des idées facultatives comme cinéma, aquarium, ramen ou rooftop.",
            "datePicker.location.areaNotSelected": "Zone non sélectionnée",
            "datePicker.location.openMap": "Ouvrez la carte pour choisir un lieu et un rayon.",
            "datePicker.location.radiusFormat": "Rayon de recherche : %d m",
            "datePicker.ideas.placeholder": "Parlez-nous de vos idées...",
            "datePicker.ideas.charactersFormat": "%d caractères",
            "common.optional": "Optionnel",
            "datePicker.cta.generate": "Générer le plan",
            "datePicker.readiness.ready": "Tout est prêt. Générez votre plan personnalisé.",
            "datePicker.readiness.adjust": "Ajustez vos préférences avant de générer.",
            "datePicker.readiness.chooseFormat": "Choisissez votre %@ pour continuer.",
            "datePicker.header.noAreaYet": "Aucune zone",
            "datePicker.header.noMoodYet": "Aucune humeur",
            "common.done": "Terminé",
            "datePicker.error.title": "Erreur de génération",
            "common.ok": "OK",
            "common.unknownError": "Erreur inconnue",
            "mood.chill": "Détente",
            "mood.romantic": "Romantique",
            "mood.fun": "Fun",
            "mood.adventure": "Aventure",
            "location.search.placeholder": "Rechercher un lieu (Shibuya, Tokyo...)",
            "location.tapMapHint": "Vous pouvez aussi toucher directement la carte pour choisir une zone.",
            "location.section.suggested": "Zones suggérées",
            "location.section.results": "Résultats de recherche",
            "location.noResultsYet": "Aucun résultat pour l’instant",
            "location.searchRadius": "Rayon de recherche",
            "location.selectedArea": "Zone sélectionnée",
            "location.pinnedArea": "Zone épinglée",
            "location.pinnedAreaFormat": "Zone épinglée (%.4f, %.4f)",
            "loading.step.finding.title": "Recherche des lieux proches",
            "loading.step.finding.subtitle": "Analyse des meilleurs lieux autour de votre zone.",
            "loading.step.matching.title": "Ajustement de l’ambiance",
            "loading.step.matching.subtitle": "Équilibrage du budget, de l’ambiance et de vos idées.",
            "loading.step.building.title": "Construction du parcours",
            "loading.step.building.subtitle": "Organisation d’un enchaînement fluide pour toute la date.",
            "loading.title": "Création de votre date",
            "loading.subtitle": "Nous choisissons les lieux, dessinons l’ambiance et construisons un plan naturel.",
            "loading.detail.nearby": "Proche",
            "loading.detail.ai": "IA",
            "loading.detail.flow": "Flow",
            "loading.progress": "Génération d’un plan personnalisé...",
            "plan.duration.hoursMinutes": "%d h %d min",
            "plan.duration.hoursOnly": "%d h",
            "plan.duration.minutesOnly": "%d min",
            "common.flexible": "Flexible",
            "plan.title": "Votre plan de date",
            "plan.defaultSummary": "Un parcours fluide et personnalisé selon votre vibe et les lieux autour de vous.",
            "plan.stats.budget": "Budget",
            "plan.stats.stops": "Étapes",
            "plan.stats.duration": "Durée",
            "plan.itinerary.title": "Itinéraire",
            "plan.itinerary.subtitle": "Un déroulé étape par étape pour tout le rendez-vous.",
            "plan.stopFormat": "Étape %d",
            "plan.whyThisStop": "Pourquoi cette étape",
            "plan.viewDetails": "Voir les détails",
            "plan.nextStop": "Étape suivante",
            "detail.addressUnavailable": "Adresse indisponible",
            "detail.selectedStop": "Étape sélectionnée",
            "detail.stopSpotlight": "Focus sur l’étape",
            "detail.stopSpotlightSubtitle": "Un lieu choisi pour que le rendez-vous reste naturel, équilibré et mémorable.",
            "detail.quickFacts": "Infos rapides",
            "detail.category": "Catégorie",
            "common.custom": "Personnalisé",
            "detail.estimated": "Estimation",
            "detail.coordinates": "Coordonnées",
            "detail.whyItWorks": "Pourquoi ça fonctionne",
            "detail.locationPreview": "Aperçu du lieu",
            "detail.tapToOpenMaps": "Touchez pour ouvrir dans Plans",
            "detail.preferGoogleMaps": "Vous préférez Google Maps ?",
            "detail.openThere": "Ouvrir là-bas",
            "detail.locationPreviewUnavailable": "Aperçu du lieu indisponible",
            "options.title": "Options",
            "options.subtitle": "Ajustez quelques préférences de l’app et choisissez la langue à utiliser.",
            "options.language.title": "Langue de l’app",
            "options.language.subtitle": "L’app démarre dans la langue de l’appareil si elle est disponible, sinon en anglais.",
            "options.language.current": "Langue actuelle",
            "options.launch.title": "Comportement au lancement",
            "options.launch.subtitle": "L’écran de présentation s’affiche uniquement au premier lancement. Ensuite, l’app ouvre directement le planificateur."
        ],
        .spanish: [
            "content.highlight.ai.title": "Creado por IA",
            "content.highlight.ai.subtitle": "Un flujo de cita pensado según tu estilo.",
            "content.highlight.nearby.title": "Lugares cercanos",
            "content.highlight.nearby.subtitle": "Selecciones inteligentes alrededor de tu zona.",
            "content.highlight.personal.title": "Toque personal",
            "content.highlight.personal.subtitle": "Incluye presupuesto, ambiente e ideas propias.",
            "content.appTitle": "Planificador de citas con IA",
            "content.hero.line1": "Planea una cita",
            "content.hero.line2": "que de verdad encaje",
            "content.hero.subtitle": "Cuéntanos tu mood, presupuesto y zona. Lo convertiremos en un plan fluido y personalizado en segundos.",
            "content.badge.aiSuggestions": "Sugerencias IA",
            "content.badge.readyInSeconds": "Listo en segundos",
            "content.card.title": "Del mood al recorrido",
            "content.card.subtitle": "Encuentra sitios cercanos, equilibra el ambiente y crea una cita con ritmo natural.",
            "content.card.localPicks": "Selección local",
            "content.card.personalized": "Personalizado",
            "content.callout.title": "Pensado para una cita fluida",
            "content.callout.subtitle": "No son solo lugares aleatorios. La app intenta crear un recorrido fácil y coherente.",
            "content.cta.startPlanning": "Empezar",
            "content.cta.caption": "Mood, presupuesto y zona. Nosotros hacemos el resto.",
            "datePicker.location.unselected": "Elegir una zona",
            "datePicker.readiness.location": "ubicación",
            "datePicker.readiness.mood": "mood",
            "datePicker.map.disabledPreview": "Mapa desactivado en vista previa",
            "datePicker.map.previewPlaceholder": "La vista previa del mapa aparecerá aquí",
            "datePicker.title": "Configuración",
            "datePicker.heading": "Crea tu cita",
            "datePicker.subtitle": "Define el mood, el presupuesto y la zona. Lo convertiremos en un plan fluido con lugares cercanos y una buena secuencia.",
            "datePicker.section.budget.title": "Presupuesto",
            "datePicker.section.budget.subtitle": "Define el presupuesto para toda la cita.",
            "datePicker.section.location.title": "Ubicación",
            "datePicker.section.location.subtitle": "Elige la zona donde debería ocurrir la cita.",
            "datePicker.section.mood.title": "Mood",
            "datePicker.section.mood.subtitle": "Elige la energía general que quieres para la cita.",
            "datePicker.section.ideas.title": "Ideas",
            "datePicker.section.ideas.subtitle": "Añade ideas opcionales como cine, acuario, ramen o rooftop.",
            "datePicker.location.areaNotSelected": "Zona no seleccionada",
            "datePicker.location.openMap": "Abre el mapa para elegir un lugar y un radio.",
            "datePicker.location.radiusFormat": "Radio de búsqueda: %d m",
            "datePicker.ideas.placeholder": "Cuéntanos tus ideas...",
            "datePicker.ideas.charactersFormat": "%d caracteres",
            "common.optional": "Opcional",
            "datePicker.cta.generate": "Generar plan",
            "datePicker.readiness.ready": "Todo está listo. Genera tu plan personalizado.",
            "datePicker.readiness.adjust": "Ajusta tus preferencias antes de generar.",
            "datePicker.readiness.chooseFormat": "Elige tu %@ para continuar.",
            "datePicker.header.noAreaYet": "Sin zona",
            "datePicker.header.noMoodYet": "Sin mood",
            "common.done": "Listo",
            "datePicker.error.title": "Error de generación",
            "common.ok": "OK",
            "common.unknownError": "Error desconocido",
            "mood.chill": "Relax",
            "mood.romantic": "Romántico",
            "mood.fun": "Divertido",
            "mood.adventure": "Aventura",
            "location.search.placeholder": "Buscar un lugar (Shibuya, Tokyo...)",
            "location.tapMapHint": "También puedes tocar directamente el mapa para elegir una zona.",
            "location.section.suggested": "Zonas sugeridas",
            "location.section.results": "Resultados de búsqueda",
            "location.noResultsYet": "Aún no hay resultados",
            "location.searchRadius": "Radio de búsqueda",
            "location.selectedArea": "Zona seleccionada",
            "location.pinnedArea": "Zona fijada",
            "location.pinnedAreaFormat": "Zona fijada (%.4f, %.4f)",
            "loading.step.finding.title": "Buscando lugares cercanos",
            "loading.step.finding.subtitle": "Analizando los mejores sitios alrededor de tu zona.",
            "loading.step.matching.title": "Ajustando el mood",
            "loading.step.matching.subtitle": "Equilibrando presupuesto, ambiente e ideas.",
            "loading.step.building.title": "Construyendo la ruta",
            "loading.step.building.subtitle": "Organizando un flujo natural para toda la cita.",
            "loading.title": "Diseñando tu cita",
            "loading.subtitle": "Estamos eligiendo lugares, definiendo el ambiente y construyendo un plan natural.",
            "loading.detail.nearby": "Cerca",
            "loading.detail.ai": "IA",
            "loading.detail.flow": "Flujo",
            "loading.progress": "Generando un plan personalizado...",
            "plan.duration.hoursMinutes": "%d h %d min",
            "plan.duration.hoursOnly": "%d h",
            "plan.duration.minutesOnly": "%d min",
            "common.flexible": "Flexible",
            "plan.title": "Tu plan de cita",
            "plan.defaultSummary": "Una ruta fluida y personalizada según tu vibe y los lugares cercanos.",
            "plan.stats.budget": "Presupuesto",
            "plan.stats.stops": "Paradas",
            "plan.stats.duration": "Duración",
            "plan.itinerary.title": "Itinerario",
            "plan.itinerary.subtitle": "Un recorrido paso a paso para toda la cita.",
            "plan.stopFormat": "Parada %d",
            "plan.whyThisStop": "Por qué esta parada",
            "plan.viewDetails": "Ver detalles",
            "plan.nextStop": "Siguiente parada",
            "detail.addressUnavailable": "Dirección no disponible",
            "detail.selectedStop": "Parada seleccionada",
            "detail.stopSpotlight": "Spot destacado",
            "detail.stopSpotlightSubtitle": "Un lugar elegido para que la cita se sienta natural, equilibrada y memorable.",
            "detail.quickFacts": "Datos rápidos",
            "detail.category": "Categoría",
            "common.custom": "Personalizado",
            "detail.estimated": "Estimado",
            "detail.coordinates": "Coordenadas",
            "detail.whyItWorks": "Por qué funciona",
            "detail.locationPreview": "Vista previa de ubicación",
            "detail.tapToOpenMaps": "Toca para abrir en Maps",
            "detail.preferGoogleMaps": "¿Prefieres Google Maps?",
            "detail.openThere": "Abrir allí",
            "detail.locationPreviewUnavailable": "Vista previa no disponible",
            "options.title": "Opciones",
            "options.subtitle": "Ajusta algunas preferencias de la app y elige el idioma que quieres usar.",
            "options.language.title": "Idioma de la app",
            "options.language.subtitle": "La app se inicia en el idioma del dispositivo cuando está disponible y usa inglés si no lo está.",
            "options.language.current": "Idioma actual",
            "options.launch.title": "Comportamiento al abrir",
            "options.launch.subtitle": "La pantalla de presentación se muestra solo la primera vez. Después, la app abre directamente el planificador."
        ],
        .japanese: [
            "content.highlight.ai.title": "AIプラン",
            "content.highlight.ai.subtitle": "雰囲気に合わせたデートの流れを作成します。",
            "content.highlight.nearby.title": "近くのスポット",
            "content.highlight.nearby.subtitle": "選んだエリア周辺から最適な候補を提案します。",
            "content.highlight.personal.title": "あなた向け",
            "content.highlight.personal.subtitle": "予算、ムード、アイデアをしっかり反映します。",
            "content.appTitle": "AIデートプランナー",
            "content.hero.line1": "ちゃんとしっくりくる",
            "content.hero.line2": "デートを計画しよう",
            "content.hero.subtitle": "ムード、予算、エリアを入力すると、自然でパーソナルなデートプランを数秒で作成します。",
            "content.badge.aiSuggestions": "AI提案",
            "content.badge.readyInSeconds": "数秒で完成",
            "content.card.title": "気分からルートへ",
            "content.card.subtitle": "近くの場所を見つけて雰囲気を整え、自然な流れのデートプランを作ります。",
            "content.card.localPicks": "周辺候補",
            "content.card.personalized": "パーソナル",
            "content.callout.title": "自然な流れのために設計",
            "content.callout.subtitle": "場所を並べるだけではなく、無理のない一貫したルートを目指します。",
            "content.cta.startPlanning": "プランを始める",
            "content.cta.caption": "ムード、予算、場所。あとはお任せください。",
            "datePicker.location.unselected": "エリアを選択",
            "datePicker.readiness.location": "場所",
            "datePicker.readiness.mood": "ムード",
            "datePicker.map.disabledPreview": "プレビューでは地図が無効です",
            "datePicker.map.previewPlaceholder": "ここに地図プレビューが表示されます",
            "datePicker.title": "デート設定",
            "datePicker.heading": "デートを作成",
            "datePicker.subtitle": "ムード、予算、エリアを設定すると、近くのスポットと自然な流れを持つデートプランを作成します。",
            "datePicker.section.budget.title": "予算",
            "datePicker.section.budget.subtitle": "デート全体の予算を設定します。",
            "datePicker.section.location.title": "場所",
            "datePicker.section.location.subtitle": "デートを行うエリアを選びます。",
            "datePicker.section.mood.title": "ムード",
            "datePicker.section.mood.subtitle": "デート全体の雰囲気を選択します。",
            "datePicker.section.ideas.title": "アイデア",
            "datePicker.section.ideas.subtitle": "映画館、水族館、ラーメン、ルーフトップなどの希望を追加できます。",
            "datePicker.location.areaNotSelected": "エリア未選択",
            "datePicker.location.openMap": "地図を開いて場所と範囲を選択してください。",
            "datePicker.location.radiusFormat": "検索半径: %d m",
            "datePicker.ideas.placeholder": "アイデアを入力してください...",
            "datePicker.ideas.charactersFormat": "%d文字",
            "common.optional": "任意",
            "datePicker.cta.generate": "プランを生成",
            "datePicker.readiness.ready": "準備が整いました。あなた向けのデートプランを生成できます。",
            "datePicker.readiness.adjust": "生成前に設定を調整してください。",
            "datePicker.readiness.chooseFormat": "続行するには%@を選択してください。",
            "datePicker.header.noAreaYet": "エリア未設定",
            "datePicker.header.noMoodYet": "ムード未設定",
            "common.done": "完了",
            "datePicker.error.title": "生成エラー",
            "common.ok": "OK",
            "common.unknownError": "不明なエラー",
            "mood.chill": "リラックス",
            "mood.romantic": "ロマンチック",
            "mood.fun": "楽しく",
            "mood.adventure": "アドベンチャー",
            "location.search.placeholder": "場所を検索 (Shibuya, Tokyo...)",
            "location.tapMapHint": "地図を直接タップしてエリアを選ぶこともできます。",
            "location.section.suggested": "おすすめエリア",
            "location.section.results": "検索結果",
            "location.noResultsYet": "まだ結果がありません",
            "location.searchRadius": "検索半径",
            "location.selectedArea": "選択したエリア",
            "location.pinnedArea": "ピン留めしたエリア",
            "location.pinnedAreaFormat": "ピン留めしたエリア (%.4f, %.4f)",
            "loading.step.finding.title": "近くのスポットを検索中",
            "loading.step.finding.subtitle": "選択したエリア周辺の最適な場所を探しています。",
            "loading.step.matching.title": "ムードを調整中",
            "loading.step.matching.subtitle": "予算、雰囲気、アイデアのバランスを取っています。",
            "loading.step.building.title": "ルートを構成中",
            "loading.step.building.subtitle": "デート全体が自然に流れるように並べています。",
            "loading.title": "デートをデザイン中",
            "loading.subtitle": "場所を選び、雰囲気を整え、自然なプランを組み立てています。",
            "loading.detail.nearby": "周辺",
            "loading.detail.ai": "AI",
            "loading.detail.flow": "流れ",
            "loading.progress": "あなた向けのプランを生成中...",
            "plan.duration.hoursMinutes": "%d時間%d分",
            "plan.duration.hoursOnly": "%d時間",
            "plan.duration.minutesOnly": "%d分",
            "common.flexible": "柔軟",
            "plan.title": "あなたのデートプラン",
            "plan.defaultSummary": "雰囲気と周辺スポットに合わせた、自然でパーソナルなルートです。",
            "plan.stats.budget": "予算",
            "plan.stats.stops": "スポット数",
            "plan.stats.duration": "所要時間",
            "plan.itinerary.title": "旅程",
            "plan.itinerary.subtitle": "デート全体のステップごとの流れです。",
            "plan.stopFormat": "スポット %d",
            "plan.whyThisStop": "このスポットを選んだ理由",
            "plan.viewDetails": "詳細を見る",
            "plan.nextStop": "次のスポット",
            "detail.addressUnavailable": "住所がありません",
            "detail.selectedStop": "選択したスポット",
            "detail.stopSpotlight": "スポット紹介",
            "detail.stopSpotlightSubtitle": "自然でバランスがよく、印象に残るデートになるよう選ばれた場所です。",
            "detail.quickFacts": "基本情報",
            "detail.category": "カテゴリ",
            "common.custom": "カスタム",
            "detail.estimated": "目安",
            "detail.coordinates": "座標",
            "detail.whyItWorks": "この場所が合う理由",
            "detail.locationPreview": "場所のプレビュー",
            "detail.tapToOpenMaps": "タップしてマップで開く",
            "detail.preferGoogleMaps": "Googleマップを使いますか？",
            "detail.openThere": "そちらで開く",
            "detail.locationPreviewUnavailable": "位置プレビューを表示できません",
            "options.title": "オプション",
            "options.subtitle": "アプリの設定を調整し、使用する言語を選択できます。",
            "options.language.title": "アプリの言語",
            "options.language.subtitle": "利用可能な場合は端末の言語で起動し、未対応なら英語になります。",
            "options.language.current": "現在の言語",
            "options.launch.title": "起動時の動作",
            "options.launch.subtitle": "紹介画面は初回起動時のみ表示されます。その後はプラン作成画面が直接開きます。"
        ],
        .chinese: [
            "content.highlight.ai.title": "AI 规划",
            "content.highlight.ai.subtitle": "根据你的氛围生成约会流程。",
            "content.highlight.nearby.title": "附近地点",
            "content.highlight.nearby.subtitle": "围绕你的区域智能推荐地点。",
            "content.highlight.personal.title": "个性化",
            "content.highlight.personal.subtitle": "会结合预算、心情和你的想法。",
            "content.appTitle": "AI 约会规划师",
            "content.hero.line1": "规划一场真正",
            "content.hero.line2": "适合你的约会",
            "content.hero.subtitle": "告诉我们你的心情、预算和区域，我们会在几秒内生成自然顺畅的个性化约会计划。",
            "content.badge.aiSuggestions": "AI 推荐",
            "content.badge.readyInSeconds": "几秒完成",
            "content.card.title": "从氛围到路线",
            "content.card.subtitle": "找到附近地点，平衡整体氛围，并生成自然流畅的约会路线。",
            "content.card.localPicks": "本地推荐",
            "content.card.personalized": "个性化",
            "content.callout.title": "为自然约会节奏而设计",
            "content.callout.subtitle": "不是简单随机地点，而是尽量生成轻松、连贯的路线。",
            "content.cta.startPlanning": "开始规划",
            "content.cta.caption": "心情、预算、地点。剩下交给我们。",
            "datePicker.location.unselected": "选择区域",
            "datePicker.readiness.location": "地点",
            "datePicker.readiness.mood": "心情",
            "datePicker.map.disabledPreview": "预览中地图不可用",
            "datePicker.map.previewPlaceholder": "地图预览会显示在这里",
            "datePicker.title": "约会设置",
            "datePicker.heading": "创建你的约会",
            "datePicker.subtitle": "设置心情、预算和区域，我们会结合附近地点生成一个顺畅自然的约会计划。",
            "datePicker.section.budget.title": "预算",
            "datePicker.section.budget.subtitle": "设置整场约会的预算范围。",
            "datePicker.section.location.title": "地点",
            "datePicker.section.location.subtitle": "选择约会发生的区域。",
            "datePicker.section.mood.title": "氛围",
            "datePicker.section.mood.subtitle": "选择你希望这次约会呈现的整体感觉。",
            "datePicker.section.ideas.title": "想法",
            "datePicker.section.ideas.subtitle": "可添加电影、水族馆、拉面、屋顶酒吧等偏好。",
            "datePicker.location.areaNotSelected": "尚未选择区域",
            "datePicker.location.openMap": "打开地图选择地点和范围。",
            "datePicker.location.radiusFormat": "搜索半径：%d 米",
            "datePicker.ideas.placeholder": "告诉我们你的想法...",
            "datePicker.ideas.charactersFormat": "%d 个字符",
            "common.optional": "可选",
            "datePicker.cta.generate": "生成计划",
            "datePicker.readiness.ready": "一切已准备好。现在可以生成你的个性化约会计划。",
            "datePicker.readiness.adjust": "生成前请先调整你的偏好。",
            "datePicker.readiness.chooseFormat": "请选择你的%@以继续。",
            "datePicker.header.noAreaYet": "尚无区域",
            "datePicker.header.noMoodYet": "尚无氛围",
            "common.done": "完成",
            "datePicker.error.title": "生成错误",
            "common.ok": "确定",
            "common.unknownError": "未知错误",
            "mood.chill": "轻松",
            "mood.romantic": "浪漫",
            "mood.fun": "有趣",
            "mood.adventure": "冒险",
            "location.search.placeholder": "搜索地点 (Shibuya, Tokyo...)",
            "location.tapMapHint": "你也可以直接点击地图来选择区域。",
            "location.section.suggested": "推荐区域",
            "location.section.results": "搜索结果",
            "location.noResultsYet": "暂无结果",
            "location.searchRadius": "搜索半径",
            "location.selectedArea": "已选区域",
            "location.pinnedArea": "已标记区域",
            "location.pinnedAreaFormat": "已标记区域 (%.4f, %.4f)",
            "loading.step.finding.title": "正在寻找附近地点",
            "loading.step.finding.subtitle": "扫描你所选区域周围最合适的地点。",
            "loading.step.matching.title": "正在匹配氛围",
            "loading.step.matching.subtitle": "平衡预算、气氛和你的想法。",
            "loading.step.building.title": "正在构建路线",
            "loading.step.building.subtitle": "安排一条自然顺畅的完整约会流程。",
            "loading.title": "正在设计你的约会",
            "loading.subtitle": "我们正在挑选地点、塑造氛围，并生成自然流畅的计划。",
            "loading.detail.nearby": "附近",
            "loading.detail.ai": "AI",
            "loading.detail.flow": "流程",
            "loading.progress": "正在生成个性化计划...",
            "plan.duration.hoursMinutes": "%d小时%d分钟",
            "plan.duration.hoursOnly": "%d小时",
            "plan.duration.minutesOnly": "%d分钟",
            "common.flexible": "灵活",
            "plan.title": "你的约会计划",
            "plan.defaultSummary": "根据你的氛围和附近地点定制的一条自然流畅路线。",
            "plan.stats.budget": "预算",
            "plan.stats.stops": "站点",
            "plan.stats.duration": "时长",
            "plan.itinerary.title": "行程",
            "plan.itinerary.subtitle": "整场约会的分步流程。",
            "plan.stopFormat": "第 %d 站",
            "plan.whyThisStop": "为什么选择这里",
            "plan.viewDetails": "查看详情",
            "plan.nextStop": "下一站",
            "detail.addressUnavailable": "地址不可用",
            "detail.selectedStop": "已选地点",
            "detail.stopSpotlight": "地点亮点",
            "detail.stopSpotlightSubtitle": "为了让约会自然、平衡且难忘而选择的地点。",
            "detail.quickFacts": "快速信息",
            "detail.category": "类别",
            "common.custom": "自定义",
            "detail.estimated": "预计花费",
            "detail.coordinates": "坐标",
            "detail.whyItWorks": "为什么适合",
            "detail.locationPreview": "位置预览",
            "detail.tapToOpenMaps": "点击以在地图中打开",
            "detail.preferGoogleMaps": "更喜欢 Google Maps？",
            "detail.openThere": "在那里打开",
            "detail.locationPreviewUnavailable": "无法显示位置预览",
            "options.title": "选项",
            "options.subtitle": "调整应用偏好并选择你想使用的语言。",
            "options.language.title": "应用语言",
            "options.language.subtitle": "应用会优先使用设备语言；如果不支持，则默认使用英语。",
            "options.language.current": "当前语言",
            "options.launch.title": "启动行为",
            "options.launch.subtitle": "介绍页只会在第一次打开应用时显示，之后会直接进入规划页面。"
        ],
        .korean: [
            "content.highlight.ai.title": "AI 추천",
            "content.highlight.ai.subtitle": "분위기에 맞는 데이트 흐름을 만들어 줍니다.",
            "content.highlight.nearby.title": "주변 장소",
            "content.highlight.nearby.subtitle": "선택한 지역 주변에서 적절한 장소를 찾아줍니다.",
            "content.highlight.personal.title": "개인화",
            "content.highlight.personal.subtitle": "예산, 분위기, 아이디어를 함께 반영합니다.",
            "content.appTitle": "AI 데이트 플래너",
            "content.hero.line1": "정말 잘 맞는",
            "content.hero.line2": "데이트를 계획하세요",
            "content.hero.subtitle": "분위기, 예산, 지역을 알려주면 몇 초 안에 자연스럽고 개인화된 데이트 플랜을 만들어 드립니다.",
            "content.badge.aiSuggestions": "AI 제안",
            "content.badge.readyInSeconds": "몇 초 안에 완료",
            "content.card.title": "분위기에서 루트까지",
            "content.card.subtitle": "가까운 장소를 찾고 분위기를 맞추어 자연스러운 데이트 흐름을 만듭니다.",
            "content.card.localPicks": "근처 추천",
            "content.card.personalized": "개인화",
            "content.callout.title": "자연스러운 데이트 흐름을 위해",
            "content.callout.subtitle": "무작위 장소 나열이 아니라, 편안하고 일관된 루트를 만들도록 설계했습니다.",
            "content.cta.startPlanning": "플랜 시작하기",
            "content.cta.caption": "분위기, 예산, 위치. 나머지는 저희가 맡습니다.",
            "datePicker.location.unselected": "지역 선택",
            "datePicker.readiness.location": "위치",
            "datePicker.readiness.mood": "분위기",
            "datePicker.map.disabledPreview": "미리보기에서는 지도가 비활성화됩니다",
            "datePicker.map.previewPlaceholder": "여기에 지도 미리보기가 표시됩니다",
            "datePicker.title": "데이트 설정",
            "datePicker.heading": "데이트 만들기",
            "datePicker.subtitle": "분위기, 예산, 지역을 설정하면 주변 장소와 자연스러운 흐름을 가진 데이트 플랜을 만들어 드립니다.",
            "datePicker.section.budget.title": "예산",
            "datePicker.section.budget.subtitle": "데이트 전체 예산 범위를 설정하세요.",
            "datePicker.section.location.title": "위치",
            "datePicker.section.location.subtitle": "데이트가 진행될 지역을 선택하세요.",
            "datePicker.section.mood.title": "분위기",
            "datePicker.section.mood.subtitle": "데이트 전체의 느낌을 선택하세요.",
            "datePicker.section.ideas.title": "아이디어",
            "datePicker.section.ideas.subtitle": "영화관, 수족관, 라멘, 루프탑 같은 힌트를 추가할 수 있습니다.",
            "datePicker.location.areaNotSelected": "지역이 선택되지 않음",
            "datePicker.location.openMap": "지도에서 장소와 반경을 선택하세요.",
            "datePicker.location.radiusFormat": "검색 반경: %d m",
            "datePicker.ideas.placeholder": "아이디어를 입력해 주세요...",
            "datePicker.ideas.charactersFormat": "%d자",
            "common.optional": "선택 사항",
            "datePicker.cta.generate": "플랜 생성",
            "datePicker.readiness.ready": "모든 준비가 끝났습니다. 맞춤형 데이트 플랜을 생성해 보세요.",
            "datePicker.readiness.adjust": "생성 전에 설정을 조정해 주세요.",
            "datePicker.readiness.chooseFormat": "계속하려면 %@을(를) 선택하세요.",
            "datePicker.header.noAreaYet": "지역 없음",
            "datePicker.header.noMoodYet": "분위기 없음",
            "common.done": "완료",
            "datePicker.error.title": "생성 오류",
            "common.ok": "확인",
            "common.unknownError": "알 수 없는 오류",
            "mood.chill": "편안함",
            "mood.romantic": "로맨틱",
            "mood.fun": "신나는",
            "mood.adventure": "모험",
            "location.search.placeholder": "장소 검색 (Shibuya, Tokyo...)",
            "location.tapMapHint": "지도를 직접 탭해서 지역을 선택할 수도 있습니다.",
            "location.section.suggested": "추천 지역",
            "location.section.results": "검색 결과",
            "location.noResultsYet": "아직 결과가 없습니다",
            "location.searchRadius": "검색 반경",
            "location.selectedArea": "선택한 지역",
            "location.pinnedArea": "고정한 지역",
            "location.pinnedAreaFormat": "고정한 지역 (%.4f, %.4f)",
            "loading.step.finding.title": "주변 장소 찾는 중",
            "loading.step.finding.subtitle": "선택한 지역 주변의 좋은 장소를 찾고 있습니다.",
            "loading.step.matching.title": "분위기 맞추는 중",
            "loading.step.matching.subtitle": "예산, 분위기, 아이디어를 균형 있게 반영하고 있습니다.",
            "loading.step.building.title": "루트 구성 중",
            "loading.step.building.subtitle": "데이트 전체가 자연스럽게 이어지도록 정리하고 있습니다.",
            "loading.title": "데이트를 디자인하는 중",
            "loading.subtitle": "장소를 고르고 분위기를 맞추며 자연스러운 플랜을 만들고 있습니다.",
            "loading.detail.nearby": "근처",
            "loading.detail.ai": "AI",
            "loading.detail.flow": "흐름",
            "loading.progress": "맞춤형 플랜을 생성하는 중...",
            "plan.duration.hoursMinutes": "%d시간 %d분",
            "plan.duration.hoursOnly": "%d시간",
            "plan.duration.minutesOnly": "%d분",
            "common.flexible": "유동적",
            "plan.title": "당신의 데이트 플랜",
            "plan.defaultSummary": "분위기와 주변 장소에 맞춘 자연스럽고 개인화된 루트입니다.",
            "plan.stats.budget": "예산",
            "plan.stats.stops": "스탑 수",
            "plan.stats.duration": "소요 시간",
            "plan.itinerary.title": "일정",
            "plan.itinerary.subtitle": "데이트 전체의 단계별 흐름입니다.",
            "plan.stopFormat": "스탑 %d",
            "plan.whyThisStop": "이 장소를 선택한 이유",
            "plan.viewDetails": "자세히 보기",
            "plan.nextStop": "다음 스탑",
            "detail.addressUnavailable": "주소를 사용할 수 없음",
            "detail.selectedStop": "선택된 장소",
            "detail.stopSpotlight": "장소 소개",
            "detail.stopSpotlightSubtitle": "자연스럽고 균형 잡히며 기억에 남는 데이트를 위해 선택된 장소입니다.",
            "detail.quickFacts": "빠른 정보",
            "detail.category": "카테고리",
            "common.custom": "사용자 지정",
            "detail.estimated": "예상 비용",
            "detail.coordinates": "좌표",
            "detail.whyItWorks": "이 장소가 잘 맞는 이유",
            "detail.locationPreview": "위치 미리보기",
            "detail.tapToOpenMaps": "탭하여 지도에서 열기",
            "detail.preferGoogleMaps": "Google 지도를 선호하시나요?",
            "detail.openThere": "거기서 열기",
            "detail.locationPreviewUnavailable": "위치 미리보기를 표시할 수 없습니다",
            "options.title": "옵션",
            "options.subtitle": "앱 설정을 조정하고 사용할 언어를 선택하세요.",
            "options.language.title": "앱 언어",
            "options.language.subtitle": "가능하면 기기 언어로 시작하고, 지원되지 않으면 영어로 시작합니다.",
            "options.language.current": "현재 언어",
            "options.launch.title": "실행 방식",
            "options.launch.subtitle": "소개 화면은 첫 실행 때만 표시되며, 이후에는 바로 플래너가 열립니다."
        ]
    ]
}
